In [1]:
import pandas as pd

In [11]:
df = pd.read_hdf('data.h5', 'all_questions')

In [15]:
df

,openness1,openness1_E,openness2,openness2_E,openness3,openness3_E,openness4,openness4_E,openness5,openness5_E,...,screenw,screenh,introelapse,testelapse,endelapse,IPC,country,lat_appx_lots_of_err,long_appx_lots_of_err,startTime
0,5,3146,5,4067,4,2959,5,3411,4,2170,...,768.0,1024.0,9.0,234.0,6,1,GB,51.5448,0.1991,2016-03-03 02:01:01
1,1,2624,4,4985,4,1684,4,3026,3,4742,...,1360.0,768.0,12.0,179.0,11,1,MY,3.1698,101.7060,2016-03-03 02:01:20
2,5,1930,5,1470,2,1644,5,1683,4,2229,...,1366.0,768.0,3.0,186.0,7,1,GB,54.9119,-1.3833,2016-03-03 02:01:56
3,4,3456,4,6665,5,1977,4,3728,3,4128,...,1920.0,1200.0,186.0,219.0,7,1,GB,51.7500,-1.2500,2016-03-03 02:02:02
4,5,8458,5,3510,5,17042,5,7029,5,2327,...,1366.0,768.0,8.0,315.0,17,2,KE,1.0000,38.0000,2016-03-03 02:02:57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015336,2,2649,4,3544,4,7577,3,3096,4,1896,...,1920.0,1080.0,3.0,160.0,10,2,US,39.9883,-75.2208,2018-11-08 12:04:58
1015337,4,2560,5,6632,5,2312,5,2376,5,2969,...,1920.0,1080.0,3.0,122.0,7,1,US,38.0000,-97.0000,2018-11-08 12:07:18
1015338,5,2121,5,2807,5,1711,5,2335,4,1609,...,1920.0,1080.0,2.0,135.0,12,6,US,36.1473,-86.7770,2018-11-08 12:07:49
1015339,5,5024,4,4664,4,4792,4,6471,3,1873,...,1920.0,1080.0,6.0,212.0,8,1,US,34.1067,-117.8067,2018-11-08 12:08:34
1015340,5,5039,5,2493,5,2302,5,5072,3,1752,...,1920.0,1080.0,3.0,176.0,9,1,US,38.0000,-97.0000,2018-11-08 12:08:45